spring:
  profiles: test
  datasource:
    druid:
      username: cicada_demo
      password: cicada_demo
      url: jdbc:mysql://localhost:3306/cicada_demo?useSSl=ture&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 5
