
spring:
  profiles:
    active: dev
  messages:
    basename: "i18n/messages"
    encoding: UTF-8
    fallback-to-system-locale: false
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
mybatis-plus:
  type-aliases-package: com.mds.cicada.core,com.company.project
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /cicada-template-api
    